// Generated by CoffeeScript 1.9.2
var BridgesApp, LocationFinder;

BridgesApp = (function() {
  function BridgesApp(base) {
    console.log('BridgesApp constructor called');
    this.canvas = document.getElementById("bridges-canvas");
    this.context = this.canvas.getContext("2d");
    this.context.drawImage(base, 0, 0);
  }

  return BridgesApp;

})();

LocationFinder = (function() {
  function LocationFinder() {}

  LocationFinder.prototype.find = function(x, y) {
    var a, b;
    a = Math.floor((x - 18) / 25);
    b = Math.floor((y - 18) / 25);
    if ((a + b) % 2 !== 0 || a < 1 || a > 15 || b < 1 || b > 15) {
      return [-1, -1];
    } else {
      return [a, b];
    }
  };

  return LocationFinder;

})();
