// Generated by CoffeeScript 1.9.2
var BridgesApp, ConnectionHelper, LocationFinder, PointsList;

window.onload = function() {
  var base;
  base = new Image();
  base.onload = (function(_this) {
    return function() {
      var bridges;
      bridges = new BridgesApp(base);
      return console.log('base.png Image.onload() called');
    };
  })(this);
  return base.src = 'base.png';
};

this.mousedown = function(e) {
  var dx, dy, px, py, x, y;
  this.canvas = document.getElementById('bridges-canvas');
  dx = this.canvas.offsetLeft;
  dy = this.canvas.offsetTop;
  px = e.pageX;
  py = e.pageY;
  x = px - dx;
  y = py - dy;
  return alert("click at " + x + ", " + y);
};

BridgesApp = (function() {
  function BridgesApp(base) {
    console.log('BridgesApp constructor called');
    this.canvas = document.getElementById("bridges-canvas");
    this.context = this.canvas.getContext("2d");
    this.context.drawImage(base, 0, 0);
    this.points = new PointsList;
  }

  return BridgesApp;

})();

PointsList = (function() {
  function PointsList() {
    var a, b, j, k, l;
    this.list = [];
    this.flatlist = [];
    for (b = j = 1; j <= 15; b = ++j) {
      if (b % 2 === 1) {
        for (a = k = 1; k <= 15; a = k += 2) {
          this.list.push([a, b]);
          this.flatlist.push(a * 100 + b);
        }
      } else {
        for (a = l = 2; l <= 14; a = l += 2) {
          this.list.push([a, b]);
          this.flatlist.push(a * 100 + b);
        }
      }
    }
  }

  PointsList.prototype.remove = function(point) {
    var i;
    alert("removing point " + point[0] + "," + point[1]);
    i = this.flatlist.indexOf(100 * point[0] + point[1]);
    alert("i = " + i);
    if (i >= 0) {
      this.list = this.list.slice(0, +(i - 1) + 1 || 9e9).concat(this.list.slice(i + 1));
      this.flatlist = this.flatlist.slice(0, +(i - 1) + 1 || 9e9).concat(this.flatlist.slice(i + 1));
    }
    alert("list.length = " + this.list.length);
    return alert("flatlist.length = " + this.flatlist.length);
  };

  return PointsList;

})();

ConnectionHelper = (function() {
  function ConnectionHelper() {
    this.vt = [[0, -2], [-1, -1], [1, -1], [-1, 1], [1, 1], [0, 2]];
    this.hz = [[-1, -1], [1, -1], [-2, 0], [2, 0], [-1, 1], [1, 1]];
  }

  ConnectionHelper.prototype.findConnectors = function(color, a, b) {
    var aa, bb, cnxx, d, deltas, dir, j, len;
    cnxx = [];
    dir = this.findVH(color, a, b);
    if (dir === 'vert') {
      deltas = this.vt;
    } else {
      deltas = this.hz;
    }
    for (j = 0, len = deltas.length; j < len; j++) {
      d = deltas[j];
      aa = a + d[0];
      bb = b + d[1];
      if (aa >= 1 && aa <= 15 && bb >= 1 && bb <= 15) {
        cnxx.push([aa, bb]);
      }
    }
    return cnxx;
  };

  ConnectionHelper.prototype.findVH = function(color, a, b) {
    if (color === 'green') {
      if (a % 2 === 1) {
        return 'vert';
      } else {
        return 'horz';
      }
    } else {
      if (a % 2 === 1) {
        return 'horz';
      } else {
        return 'vert';
      }
    }
  };

  return ConnectionHelper;

})();

LocationFinder = (function() {
  function LocationFinder() {}

  LocationFinder.prototype.find = function(x, y) {
    var a, b;
    a = Math.floor((x - 18) / 25);
    b = Math.floor((y - 18) / 25);
    if ((a + b) % 2 !== 0 || a < 1 || a > 15 || b < 1 || b > 15) {
      return [-1, -1];
    } else {
      return [a, b];
    }
  };

  return LocationFinder;

})();
