// Generated by CoffeeScript 1.9.2
var BridgesApp, LocationFinder, PointsList;

this.mousedown = function(e) {
  var dx, dy, px, py, x, y;
  this.canvas = document.getElementById('bridges-canvas');
  dx = this.canvas.offsetLeft;
  dy = this.canvas.offsetTop;
  px = e.pageX;
  py = e.pageY;
  x = px - dx;
  y = py - dy;
  return alert("click at " + x + ", " + y);
};

BridgesApp = (function() {
  function BridgesApp(base) {
    console.log('BridgesApp constructor called');
    this.canvas = document.getElementById("bridges-canvas");
    this.context = this.canvas.getContext("2d");
    this.context.drawImage(base, 0, 0);
    this.points = new PointsList;
  }

  return BridgesApp;

})();

PointsList = (function() {
  function PointsList() {
    var a, b, i, j, k;
    this.list = [];
    for (b = i = 1; i <= 15; b = ++i) {
      if (b % 2 === 1) {
        for (a = j = 1; j <= 15; a = j += 2) {
          this.list.push([a, b]);
        }
      } else {
        for (a = k = 2; k <= 14; a = k += 2) {
          this.list.push([a, b]);
        }
      }
    }
  }

  return PointsList;

})();

LocationFinder = (function() {
  function LocationFinder() {}

  LocationFinder.prototype.find = function(x, y) {
    var a, b;
    a = Math.floor((x - 18) / 25);
    b = Math.floor((y - 18) / 25);
    if ((a + b) % 2 !== 0 || a < 1 || a > 15 || b < 1 || b > 15) {
      return [-1, -1];
    } else {
      return [a, b];
    }
  };

  return LocationFinder;

})();
