// Generated by CoffeeScript 1.9.2
describe("Points status object", function() {
  it("should generate a fresh list of open points", function() {
    var list;
    this.points = new PointsList;
    list = this.points.list;
    expect(list.length).toEqual(113);
    expect(list).toContain([1, 1]);
    expect(list).toContain([15, 1]);
    expect(list).toContain([1, 15]);
    expect(list).toContain([15, 15]);
    expect(list).toContain([6, 12]);
    expect(list).toContain([4, 14]);
    expect(list).toContain([11, 3]);
    expect(list).toContain([8, 10]);
    expect(list).toContain([5, 13]);
    return expect(list).toContain([9, 7]);
  });
  it("should remove an item from an array", function() {
    this.points = new PointsList;
    expect(this.points.list.length).toEqual(113);
    expect(this.points.flatlist.length).toEqual(113);
    this.points.remove(18, 32);
    expect(this.points.flatlist.length).toEqual(113);
    expect(this.points.list.length).toEqual(113);
    this.points.remove(4, 10);
    expect(this.points.list.length).toEqual(112);
    expect(this.points.flatlist.length).toEqual(112);
    this.points.remove(13, 7);
    expect(this.points.list.length).toEqual(111);
    expect(this.points.flatlist.length).toEqual(111);
    this.points.remove(12, 8);
    expect(this.points.list.length).toEqual(110);
    expect(this.points.flatlist.length).toEqual(110);
    this.points.remove(5, 3);
    expect(this.points.list.length).toEqual(109);
    return expect(this.points.flatlist.length).toEqual(109);
  });
  return it("should determine if an item is in the list", function() {
    this.points = new PointsList;
    expect(this.points.listContains(6, 12)).toBe(true);
    expect(this.points.listContains(4, 14)).toBe(true);
    expect(this.points.listContains(13, 7)).toBe(true);
    expect(this.points.listContains(5, 3)).toBe(true);
    expect(this.points.listContains(6, 7)).toBe(false);
    expect(this.points.listContains(12, 1)).toBe(false);
    expect(this.points.listContains(4, 88)).toBe(false);
    expect(this.points.listContains(43, 5)).toBe(false);
    this.points.remove(5, 3);
    expect(this.points.listContains(5, 3)).toBe(false);
    this.points.remove(13, 7);
    expect(this.points.listContains(13, 7)).toBe(false);
    this.points.remove(4, 14);
    expect(this.points.listContains(4, 14)).toBe(false);
    this.points.remove(6, 12);
    return expect(this.points.listContains(6, 12)).toBe(false);
  });
});
